"""empty message

Revision ID: 3ef62e9d614e
Revises: 4cff122fb644
Create Date: 2019-07-11 22:02:24.768306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef62e9d614e'
down_revision = '4cff122fb644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_like', sa.Boolean(), nullable=False))
    op.drop_column('likes', 'num_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('num_likes', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('likes', 'is_like')
    # ### end Alembic commands ###
