"""empty message

Revision ID: 7350097cf856
Revises: 7e5cae9f1015
Create Date: 2019-07-11 20:15:28.407319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7350097cf856'
down_revision = '7e5cae9f1015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('initial_investment', sa.Integer(), nullable=False))
    op.drop_column('investments', 'intiial_investment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('intiial_investment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('investments', 'initial_investment')
    # ### end Alembic commands ###
