"""empty message

Revision ID: 74e27aac30c1
Revises: 3ef62e9d614e
Create Date: 2019-07-12 12:05:03.288676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e27aac30c1'
down_revision = '3ef62e9d614e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('initial_worth', sa.Integer(), nullable=True))
    op.drop_column('blogposts', 'num_dislikes')
    op.drop_column('blogposts', 'num_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('num_likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogposts', sa.Column('num_dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogposts', 'initial_worth')
    # ### end Alembic commands ###
