"""empty message

Revision ID: 7e5cae9f1015
Revises: 806480d85ca7
Create Date: 2019-07-11 17:11:36.472613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5cae9f1015'
down_revision = '806480d85ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intiial_investment', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['blogposts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    # ### end Alembic commands ###
