"""empty message

Revision ID: 806480d85ca7
Revises: 03562febc62b
Create Date: 2019-07-11 15:50:18.451244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806480d85ca7'
down_revision = '03562febc62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('investment_active', sa.Boolean(), nullable=True))
    op.add_column('blogposts', sa.Column('market_active', sa.Boolean(), nullable=True))
    op.add_column('blogposts', sa.Column('num_dislikes', sa.Integer(), nullable=True))
    op.add_column('blogposts', sa.Column('num_likes', sa.Integer(), nullable=True))
    op.drop_column('blogposts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('blogposts', 'num_likes')
    op.drop_column('blogposts', 'num_dislikes')
    op.drop_column('blogposts', 'market_active')
    op.drop_column('blogposts', 'investment_active')
    # ### end Alembic commands ###
